### ISSUE TITLE
Error from JNI native library

### ISSUE THREAD

**Issue by michkhol** [tlk00/BitMagic#29]
While running BitCountTest on Linux:
```java: /home/kholodov/git/BitMagic/lang-maps/jni/../../src/bm.h:1242: bool bm::bvector<A>::set_bit(bm::id_t, bool) [with Alloc = libbm::mem_alloc<libbm::block_allocator, libbm::ptr_allocator>; bm::id_t = unsigned int]: Assertion `n < size_' failed.```

**Comment by tlk00** [comment]
Should be now resolved in master

**Comment by tlk00** [comment]
Should be good now
