### ISSUE TITLE
Possible int overflow in encoding.h when compiling on a 32-bit compiler

### ISSUE THREAD

**Issue by mmastrac** [tlk00/BitMagic#30]
When compiling w/-Wconversion:

Error: `Implicit conversion loses integer precision: 'unsigned long long' to 'bm::word_t' (aka 'unsigned int')`

As the type of `bm::word_t` is `unsigned int` (ie: 32-bits on a 32-bit platform), this function could silently truncate the result of the data. I don't actually use this code so I don't have a test-case available to prove it, but it looks like a reasonable warning.

```inline bm::id64_t decoder::get_64()
{
#if (BM_UNALIGNED_ACCESS_OK == 1)
	bm::id64_t a = *((bm::id64_t*)buf_);
#else
	bm::word_t a = buf_[0]+
                   ((bm::id64_t)buf_[1] << 8)  +
                   ((bm::id64_t)buf_[2] << 16) +
                   ((bm::id64_t)buf_[3] << 24) +
                   ((bm::id64_t)buf_[4] << 32) +
                   ((bm::id64_t)buf_[5] << 40) +
                   ((bm::id64_t)buf_[6] << 48) +
                   ((bm::id64_t)buf_[7] << 56);
#endif
    buf_+=sizeof(a);
    return a;
}
```

**Comment by tlk00** [comment]
Agreed, it is totally reasonable even in 64-bit compile.
It's a legit bug. The code is a victim of Intel unaligned access OK mode.

What is the platform you use. If you happen to be on x86, please help me to identify why
BM_UNALIGNED_ACCESS_OK was not set there. (Must be some combination of OS/compiler prevented it).

Thank you for reporting it!

**Comment by mmastrac** [comment]
No problem. Currently building on iOS (arm32/arm64) which doesn't support unaligned access.

**Comment by tlk00** [comment]
I think i fixed the issue in the master.

**Comment by mattfs** [comment]
Confirmed fixed!
