### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by renau** [tlk00/BitMagic#37]
bm/encoding.h:461:24: warning: assigning field to itself [-Wself-assign-field]
            used_bits_ ^= used_bits_;

**Comment by tlk00** [comment]
Harmless, but I will take an action to silence it.

**Comment by renau** [comment]
I agree, but I am trying to kill all my warnings, and this one keeps popping all the time.
(btw, any plan to support 64bit index BM instead of 32bit?)

**Comment by tlk00** [comment]
It should be fixed now, please try the master branch

**Comment by renau** [comment]
Neat, now no warnings.

**Comment by tlk00** [comment]
>btw, any plan to support 64bit index BM instead of 32bit?

Master branch now supports 64-bit (48-bits actually) index. Release prep is in progress.
