### ISSUE TITLE
JNI integration

### ISSUE THREAD

**Issue by michkhol** [tlk00/BitMagic#4]
The separate memory management of JVM and the library leads to the very awkward resource management in the Java code, as each created bitvector needs to be destroyed explicitly. The problem can be mitigated by having a custom implementation of the `new` and `delete` methods as outlined in the attached file.
[sorensen.pdf](https://github.com/tlk00/BitMagic/files/1309154/sorensen.pdf)

**Comment by michkhol** [comment]
Sample header file attached
[org_tlk00_bitmagic_BVector0.zip](https://github.com/tlk00/BitMagic/files/1311397/org_tlk00_bitmagic_BVector0.zip)

**Comment by tlk00** [comment]
Attempts to implement Java friendly allocation failed because the technique described in the Sorensen article did not work (JVM moves JNI allocated memory blocks).
