### ISSUE TITLE
Packing 2 bits values into a bigger Datatype(INT64)

### ISSUE THREAD

**Issue by Darshvino** [tlk00/BitMagic#68]
Hi, 

Thank you for all your work and all the resources you had provided.

Is there any reference to efficiently pack the 2 bits into a larger data type(basically int64)?

A = 0000.........10(64 bit), B = 0000........11(64 bit), C = 0000........01, and so on, these are int64 values containing 2-bit values.

So, I want to pack them in an int64 datatype(32 2-bit values)
Z = 101101...........(int64 value, containing packed values of A, B, C, D, .............. )

I want to perform this efficiently. So It would be helpful if you can help me with some references.

Thanks in advance!

**Comment by tlk00** [comment]
BM library does not provide this functionality.

**Comment by tlk00** [comment]
Closing it as a general question, not related to BM functionality per se.
