### ISSUE TITLE
Documentation involving `svector_u32` and limits of DNA compression

### ISSUE THREAD

**Issue by rlorigro** [tlk00/BitMagic#74]
Hi, 

Probably I am missing something obvious, but the term `svector_u32` does not appear in any of the header files in `BitMagic/src` but when I attempt to follow one of [your examples](http://www.bitmagic.io/dna-compare.html) it appears as a type. Is the example out of date? If so what is the correct usage?

For completeness here is the example:
```
            const char* s = "ATGTCNNNNNTATA";
            svector_u32 sv;
            {
                svector_u32::back_insert_iterator bi = sv.get_back_inserter();
                for (unsigned i = 0; s[i]; ++i)
                {
                    bi = DNA2int(s[i]);
                }
                bi.flush();
            }
            sv.optimize(); // this will RLE compress the sparse (N) plane
```
My goal is to be able to selectively deserialize as well, but that example also makes use of `svector_u32`.

Thanks

**Comment by tlk00** [comment]
svector_u32  is defined in specific examples like xsample06.cpp svsample08 (09, 10). 
This tyedef is not part of BM headers, but it is trivial to define. Probably need a better code comments on the Web page.

**Comment by rlorigro** [comment]
Thanks @tlk00, with that pointer I got things working. My next goal is to estimate the compression ratio, so I have written the following code:
```
typedef bm::sparse_vector<bm::id_t, bm::bvector<> > svector_u32;

static const array<uint32_t,128> base_to_index = {
        4,4,4,4,4,4,4,4,4,4,      // 0
        4,4,4,4,4,4,4,4,4,4,      // 10
        4,4,4,4,4,4,4,4,4,4,      // 20
        4,4,4,4,4,4,4,4,4,4,      // 30
        4,4,4,4,4,4,4,4,4,4,      // 40
        4,4,4,4,4,4,4,4,4,4,      // 50
        4,4,4,4,4,0,4,1,4,4,      // 60  A = 65, C = 67
        4,2,4,4,4,4,4,4,4,4,      // 70  G = 71, N = 78
        4,4,4,4,3,4,4,4,4,4,      // 80  T = 84
        4,4,4,4,4,4,4,4,4,4,      // 90
        4,4,4,4,4,4,4,4,4,4,      // 100
        4,4,4,4,4,4,4,4,4,4,      // 110
        4,4,4,4,4,4,4,4           // 120
};


int main(){
    path ref_fasta = "/home/user/data/human/reference/chm13v2.0.fa";

    vector<svector_u32> bit_sequences;

    for_sequence_in_fasta_file(ref_fasta, [&](const Sequence& s){
        cerr << "Reading: " << s.name << '\n';

        bit_sequences.emplace_back();
        auto& b = bit_sequences.back();
        svector_u32::back_insert_iterator bi = b.get_back_inserter();

        for (unsigned i = 0; s.sequence[i]; ++i)
        {
            bi = base_to_index.at(toupper(s.sequence[i]));
        }
        bi.flush();
        b.optimize(); // this will RLE compress the sparse (N) plane

        struct svector_u32 ::statistics st;
        b.calc_stat(&st);

        cerr << "\teffective_size: " << b.effective_size() << '\n';
        cerr << "\tsize: " << b.size() << '\n';
        cerr << "\tmemory_used: " << st.memory_used << '\n';
        cerr << "\tcompression_ratio: " << float(s.sequence.size()) / float(st.memory_used) << '\n';
    });

    return 0;
}

```

And from this I get some output:
```
Reading: chr1
        effective_size: 248387328
        size: 248387328
        memory_used: 62173568
        compression_ratio: 3.99506
Reading: chr2
        effective_size: 242696752
        size: 242696752
        memory_used: 60748160
        compression_ratio: 3.99513
```
Which appears to indicate a compression ratio corresponding almost exactly to a 2bit encoding (8/2 = 4), assuming that this `memory_used` is in bytes. Is this what you expect? Is there any way to your knowledge that would be capable of compressing genomic sequence beyond this?

I also noticed that short sequences tend to increase in size, as can be seen in the mitochondrial chromosome:
```
Reading: chrM
        effective_size: 16569
        size: 16569
        memory_used: 20640
        compression_ratio: 0.802762
```
and also in an even smaller subsequence I extracted, it grows quite a lot:
```
Reading: chr20:47,474,337-47,476,723
        effective_size: 2387
        size: 2387
        memory_used: 15008
        compression_ratio: 0.159049
```

Is this increase in size expected?

Thanks

**Comment by rlorigro** [comment]
(apologies for changing the subject of the issue, maybe can rename it once it is complete)

**Comment by tlk00** [comment]
Yes, the basic example perfectly illustrates 2NA compression where BM is used as a building block.

It can also be used for alignments or reference based sequence compression, which of cause would be beyond a simple example. What can also be improved here is applying BWT upfront (or any other reversible sorting transform), in this case BM codec is able to use patterns of sequence bases and encode better than ATGC. Same story here, such cases would be more complex than a simple example.

I think sequence compression beyond 2NA should be combination of different methods beyond just one codec (such as BM).

**Comment by rlorigro** [comment]
I see thanks. Do you have an explanation for why the size appears to increase for the shorter sequences? Is there just some overhead in the data structure which cannot be avoided?

**Comment by tlk00** [comment]
Yes, internal serialization structure is quite complex. It accounts for changes in patterns (thus used codec), provide an ability to extract ranges, without decompressing the whole vectors (bit-vectors or sparse) and various other (necessary) overheads important for big data, future codec extensions, etc, etc... 
BM is more universal than just plain nucleotide compressor, thus it is really a trade off.

**Comment by rlorigro** [comment]
That makes sense, thank you for the quick/helpful information

**Comment by tlk00** [comment]
NP. Thank you for your interest.
